### ISSUE TITLE
pyproject.toml

### ISSUE THREAD

**Issue by buhtz** [boileaum/datetimejson#1]
Because this "package" is fresh and new I would recommend to use a pyproject.toml file and remove setup.cfg/py

https://setuptools.pypa.io/en/latest/userguide/pyproject_config.html

If you need a real life example
https://codeberg.org/buhtz/buhtzology/src/branch/develop

**Comment by boileaum** [comment]
Thanks for the suggestion. Solving this was as simple as:

```bash
pip install ini2toml[lite]
ini2toml setup.cfg > pyproject.toml
rm setup.*
```
